name: Behat

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'
  pull_request: ~

env:
  COMPOSER_ROOT_VERSION: dev-master

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          # PHP 8.1 FPM segfaults with JIT enabled
          ini-values: opcache.jit=disable

      # Install Flex as a global dependency to enable usage of extra.symfony.require
      # while keeping Flex recipes from applying
      - run: composer global config --no-plugins allow-plugins.symfony/flex true
      - run: composer global require --no-scripts symfony/flex

      - run: composer config extra.symfony.require ~6.4.0

      - run: composer update --prefer-dist

      - run: ./tests/prepare_behat.sh > /dev/null 2>&1 &

      # Sleep to allow the script to download Chrome WebDriver
      - run: sleep 15

      - run: composer behat-headless
